backend:
  name: git-gateway
  branch: master
  repo: syrkis/liederley
  site_domain: liederley.com

media_folder: static/images
public_folder: /images

collections:
  - name: "pieces"
    label: "pieces"
    folder: "src/lib/pieces"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "slug"
        label: "Slug"
        widget: "string"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "images"
        label: "Images"
        widget: "list"
        fields:
          - name: "image"
            label: "Image"
            widget: "image"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "price"
        label: "Price"
        widget: "number"
      - name: "measurements"
        label: "Measurements"
        widget: "list"
        fields:
          - name: "measurement"
            label: "Measurement"
            widget: "string"