backend:
  name: git-gateway
  branch: master
  repo: syrkis/liederley
  site_domain: liederley.com

media_folder: static/images
public_folder: /images

collections:
  - name: "pieces"
    label: "pieces"
    folder: "src/lib/pieces"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "price", label: "Price", widget: "number" }